name: Build TempoDiPomo App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        goos: [linux, darwin, windows]
        goarch: [amd64]
        exclude:
          - os: ubuntu-latest
            goos: darwin
          - os: ubuntu-latest
            goos: windows
          - os: macos-latest
            goos: linux
          - os: macos-latest
            goos: windows
          - os: windows-latest
            goos: linux
          - os: windows-latest
            goos: darwin

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.24.1'

    - name: Install build dependencies (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libayatana-appindicator3-dev

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go mod tidy  # Ensure go.mod is clean and fetches dependencies
        if [ "$GOOS" = "windows" ]; then
          go build -o tempodipomo.exe
        else
          go build -o tempodipomo
        fi

    - name: Install nfpm (Linux only)
      if: matrix.goos == 'linux'
      run: |
        curl -sfL https://github.com/goreleaser/nfpm/releases/download/v2.35.1/nfpm_2.35.1_Linux_x86_64.tar.gz | tar xz
        sudo mv nfpm /usr/local/bin/

    - name: Build DEB package (Linux only)
      if: matrix.goos == 'linux'
      run: nfpm pkg --packager deb --target tempodipomo_${{ github.run_number }}_amd64.deb

    - name: Build RPM package (Linux only)
      if: matrix.goos == 'linux'
      run: nfpm pkg --packager rpm --target tempodipomo-${{ github.run_number }}-1.x86_64.rpm

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tempodipomo-${{ matrix.goos }}-${{ matrix.goarch }}
        path: |
          tempodipomo
          tempodipomo.exe
          tempodipomo_${{ github.run_number }}_amd64.deb
          tempodipomo-${{ github.run_number }}-1.x86_64.rpm

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        files: |
          artifacts/tempodipomo-darwin-amd64/tempodipomo
          artifacts/tempodipomo-linux-amd64/tempodipomo
          artifacts/tempodipomo-linux-amd64/tempodipomo_${{ github.run_number }}_amd64.deb
          artifacts/tempodipomo-linux-amd64/tempodipomo-${{ github.run_number }}-1.x86_64.rpm
          artifacts/tempodipomo-windows-amd64/tempodipomo.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}